### ISSUE TITLE
Face distortion in outputs

### ISSUE THREAD

**Issue by Carinazhao22** [google/nerfies#7]
Hi, I have used colab demo to run on my dataset. But people's face has some distortion in the predicted results. I cannot figure out the reasons. Is it because I didn’t train enough or should be related to my dataset?

**Comment by keunhong** [comment]
Hi, the Colab demo doesn't have the elastic regularization loss enabled due to SVD not being efficient on TPU.
You can try training on the Colab GPU (which will probably be quite slow) or on your own machine with the elastic regularization enabled. The elastic loss is already enabled in the predefined configurations mentioned in the readme.

You can also try to re-capture your sequence with more angles so that there is less ambiguity in the capture if you want to continue without the elastic regularization.

**Comment by Carinazhao22** [comment]
I got it. Thank you!
